db:
  repository: public.ecr.aws/g1o9h9r6/chungmin-lab
  tag: db-v1
  replicas: 1

redis:
  repository: public.ecr.aws/g1o9h9r6/chungmin-lab
  tag: redis-v1
  replicas: 1

app:
  repository: public.ecr.aws/g1o9h9r6/chungmin-lab
  tag: app-v1
  replicas: 1

nginx:
  repository: nginx
  tag: latest
  replicas: 1


ingress:
  healthCheckPath: /healthz
  host: app.chungmin.store
  certificateArn: arn:aws:acm:ap-northeast-2:862016452072:certificate/6c66f45a-73d1-4ba2-a9e5-4e5a6396f41d
  group:
    name: shared-alb
    order: "10"
